import Head from "next/head";
import Image from "next/image";

import hero from "../assets/heroimage320.png";
import hsbc from "../assets/hsbc-logo.svg";
import santander from "../assets/santander-logo.svg";
import bbva from "../assets/bbva-logo.svg";
import flagIcon from "../assets/flag-icon.svg";
import supportIcon from "../assets/support-icon.svg";
import walletIcon from "../assets/wallet-icon.svg";
import lockIcon from "../assets/lock-icon.svg";
import laptop from "../assets/laptop.png";
import countries from "../assets/countries.png";

import Button from "../components/Button";
import ButtonInverse from "../components/ButtonInverse";
import FeatureItem from "../components/FeatureItem";
import NumberItem from "../components/NumberItem";
import Form from "../components/Form";
import Contact from "../components/Contact";

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<main className={"px-[18px]"}>
				<section className='grid grid-cols-4 gap-x-3'>
					<Image
						className='col-span-full plugin-icon mb-6 xs:mb-4 sm:mb-10 justify-self-center'
						src={hero}
						alt='Girl waving with payment messages around'
					/>
					<div className='typo-display-2 col-span-full font-main text-center text-text-1 sm:font-medium'>
						Receive payments from your stores safely
					</div>
					<div className='col-span-full text-center mt-[18px] sm:mt-8 text-text-2 typo-body-1 leading-[165%]'>
						Implement a payment gateway for your online store. fast, safe and
						hassle-free. Start billing today without having any requirements.
					</div>

					<div className='flex col-span-full justify-evenly mt-[18px] sm:mt-16'>
						<Button>Download</Button>
						<ButtonInverse>contact</ButtonInverse>
					</div>
				</section>
				<section className='flex flex-col justify-center mt-[50px]'>
					<div className='typo-body-1 text-primary-blue text-center sm:text-left mb-[12px]'>
						supported banks
					</div>
					<div className='full-bleed-2 bg-background-2 flex justify-evenly items-center h-10 sm:h-[70px]'>
						<div className='relative h-'>
							<Image className='' src={santander} alt='santander bank logo' />
						</div>
						<Image src={hsbc} alt='hsbc bank logo' />
						<Image src={bbva} alt='bbva logo' />
					</div>
				</section>
				<section className='grid grid-cols-4 mt-[52px] font-bold gap-x-[18px]'>
					<div className='typo-heading-1 col-span-3'>
						<span className='top-line'>The</span> best payment solutions for you
					</div>
					<div className='typo-body-1 font-normal text-text-2 col-span-full mt-[18px] text-justify'>
						Fastwpay is an exclusive payment gateway plugin for
						<span className='font-bold text-primary-blue'> Woocommerce</span>,
						made for all those entrepreneurs, startups and companies that would
						like to start charging for their online business without having to
						comply with all the bureaucracy involved in hiring any provider of
						this service.
					</div>

					<ButtonInverse className='mt-[18px] col-span-2 self-start text-left'>
						Get started
					</ButtonInverse>
				</section>

				<section className='section-features grid grid-cols-4 gap-x-3 gap-y-5 mt-16'>
					<FeatureItem
						className='col-span-2'
						src={flagIcon}
						title={"Start now"}
						content={"You only need basic information."}
					/>
					<FeatureItem
						className='col-span-2'
						src={lockIcon}
						title={"Security"}
						content={"Security system with high level of data encryption."}
					/>

					<FeatureItem
						className='col-span-2'
						src={walletIcon}
						title={"Admin Panel"}
						content={"Manage your information and API keys from your account."}
					/>

					<FeatureItem
						className='col-span-2'
						src={supportIcon}
						title={"Support"}
						content={"Contact us for information and usage support."}
					/>
				</section>

				<section className=''>
					<div className='typo-heading-1 font-bold mt-[86px]'>
						<span className='top-line'>How</span> to install & activate
					</div>
					<div className='content text-justify mt-4 typo-body-1 font-normal text-text-color-2'>
						If it is the first time that you install a plugin for wordpress,
						then we explain in 3 simple steps how you can do it.
					</div>
					<ButtonInverse className='mt-4'>Get started</ButtonInverse>

					<Image
						className='-translate-x-5 mt-9'
						src={laptop}
						alt='laptop with screenshot'
					/>

					<div className='grid grid-cols-1 gap-y-8 mt-14'>
						<NumberItem
							className='grid grid-cols-4 gap-x-[18px]'
							number={"01."}
							title={"Download the file"}
							content={[
								<span className='font-bold text-primary-blue underline'>
									<a href='#'>Download </a>
								</span>,
								"the fastwpay.zip file on your computer.",
							]}
						/>
						<NumberItem
							className='grid grid-cols-4 gap-x-[18px]'
							number={"02."}
							title={"Upload the plugin in wordpress"}
							content={[
								"In the WordPress panel of your store website, go to the ",
								<span className='font-bold text-primary-blue'>
									plugins tab
								</span>,
								", press the ",
								<span className='font-bold text-primary-blue'>
									upload plugin
								</span>,
								" button and upload the fastwpay.zip file.",
							]}
						/>

						<NumberItem
							className='grid grid-cols-4 gap-x-[18px]'
							number={"03."}
							title={"Insert the api key"}
							content={[
								"To activate, create an API key in your Fastwpay account and copy it. Then go to the ",
								<span className='font-bold text-primary-blue'>
									settings tab
								</span>,
								" in your Wordpress panel of your store, paste in the API key field and save the changes.",
							]}
						/>
					</div>
				</section>
				<section className=' bg-background-2 full-bleed-2 mt-12 pt-8 grid grid-cols-4 gap-x-[18px] pb-8'>
					<div className='typo-heading-1 font-bold text-center mb-[18px] col-span-full'>
						Free to install & use
					</div>
					<div className='typo-body-1 leading-[165%] text-center text-text-2 mb-[18px] col-span-full'>
						To use it you don't need to buy it, it's completely free, and you
						can use it in all the online stores you want. Fastwpay only charges
						a small commission of 1.5% per purchase made.
					</div>
					<Button className='self-center col-span-2 col-start-2'>
						Download
					</Button>
				</section>
				<section className='grid grid-cols-4 gap-x-3'>
					<div className='typo-heading-1 font-bold mt-[84px] mb-[18px] col-span-full'>
						<span className='top-line'>Countries</span> where it works
					</div>
					<div className='typo-body-1 leading-[165%] mb-[18px] col-span-full'>
						To have an account in Fastwpay, the bank account of the owner of the
						online store must be located in
						<span className='font-bold text-primary-blue'> Spain</span>,
						<span className='font-bold text-primary-blue'> France</span>, or
						<span className='font-bold text-primary-blue'> Germany</span>.
					</div>
					<ButtonInverse className='col-span-2 text-left'>
						Get started
					</ButtonInverse>
					<Image
						className='col-span-full justify-self-center mt-11'
						src={countries}
						alt='image with spain france and germany orbitating'
					/>
				</section>
				<section className='mt-20'>
					<Form />
					<Contact />
				</section>
			</main>
		</>
	);
}
